name: Deploy to o2switch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa teneur.o2switch.net >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run build
          npm run prod

      - name: Deploy to o2switch
        run: |
          rsync -avz --exclude='.git' --exclude='node_modules' --exclude='vendor' ./ coad2295@teneur.o2switch.net:/public_html/master1.adriencompare.com/
          ssh coad2295@teneur.o2switch.net "cd /public_html/master1.adriencompare.com/ && php artisan migrate:fresh --seed"

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
